name: Build and Publish App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Generate package-lock.json
        run: |
          echo "Generating package-lock.json if missing..."
          npm install --package-lock-only

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      - name: Build the App
        run: |
          echo "Building the application..."
          npm run build

      - name: Package the App
        run: |
          echo "Packaging the application..."
          npm run dist

      - name: Extract Version
        id: extract_version
        run: |
          echo "Extracting version from package.json..."
          echo "VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Shared-OBS-Control-${{ env.VERSION }}
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      - name: Extract Version
        id: extract_version
        run: |
          echo "Extracting version from package.json..."
          echo "VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV

      - name: Publish Release
        env:
          GH_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: |
          echo "Publishing release for version ${{ env.VERSION }}..."
          npm run dist -- --publish=always
